# Generated by Django 2.2.1 on 2019-06-04 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ("Native_Service", "0001_initial"),
        ("Native_Service", "0002_nativepost_file"),
        ("Native_Service", "0003_auto_20190603_1736"),
        ("Native_Service", "0004_auto_20190603_1751"),
        ("Native_Service", "0005_remove_nativepost_file"),
        ("Native_Service", "0006_nativepost_file"),
        ("Native_Service", "0007_auto_20190603_1804"),
        ("Native_Service", "0008_auto_20190604_0728"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NativePost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("date_to_be_done", models.DateTimeField()),
                ("description", models.CharField(max_length=500)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(default=django.utils.timezone.now, max_length=40),
                ),
                (
                    "name",
                    models.CharField(default=django.utils.timezone.now, max_length=20),
                ),
            ],
        )
    ]
