# Generated by Django 2.2.1 on 2019-06-06 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("Native_Service", "0003_date_to_be_done_field_changed")]

    operations = [
        migrations.RemoveField(model_name="nativepost", name="date"),
        migrations.AddField(
            model_name="nativepost",
            name="date_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
