# Generated by Django 2.2.1 on 2019-06-07 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("Native_Service", "0004_date_time_field_changed")]

    operations = [
        migrations.AddField(
            model_name="nativepost",
            name="secret_key",
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        )
    ]
