# Generated by Django 2.2.2 on 2019-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Native_Service', '0005_secret_key_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativepost',
            name='date_to_be_done',
            field=models.DateField(),
        ),
    ]
