# Generated by Django 2.2.2 on 2019-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Native_Service", "0006_auto_20190613_1052")]

    operations = [
        migrations.AlterField(
            model_name="nativepost",
            name="date_to_be_done",
            field=models.DateTimeField(),
        )
    ]
