# Generated by Django 2.2.2 on 2019-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Native_Service", "0007_datetimefield_back_instead_datefiled")]

    operations = [
        migrations.AlterField(
            model_name="nativepost",
            name="date_time",
            field=models.DateField(auto_now_add=True),
        )
    ]
