# Generated by Django 2.2.2 on 2019-06-14 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Native_Service', '0009_NativePost_model_fixed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpricing',
            name='secret_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
